name: meta_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - pip=23.2.1
  - python=3.10.12
  - pytorch=2.0.0=py3.10_cuda11.8_cudnn8.7.0_0
  - rdkit=2022.03.5
  - typing_extensions
  - pip:
      - botorch==0.8.1
      - dgl==1.1.2+cu118
      - dpu-utils==0.6.1
      - gpytorch==1.9.1
      - higher==0.2.1
      - jaxtyping==0.2.21
      - more-itertools==10.1.0
      - pytorchtools==0.0.2
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - torch-scatter==2.1.1
      - tqdm==4.66.1
      - ujson==5.10.0

